/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.5/userguide/building_swift_projects.html in the Gradle documentation.
 */

rootProject.name = "OOP23-roofsense"


plugins {
    /*
     * Git hooks configuration
     */
    id("org.danilopianini.gradle-pre-commit-git-hooks") version "2.0.0"
}

gitHooks {
    preCommit {
        tasks("check -q")
    }
    // commitMsg {
    //     // Configuration, with conventional commits support
    // } 
    createHooks(true)
}
