/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.roofsense;

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // @Test
    // void TestApp() {
    //     App classUnderTest = new App();
    // }
}
